import Footer from '@/component/footer/Footer'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/Component/Navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>
        <div>
          {children}
        </div>
        <div>
          <Footer></Footer>
        </div>


      </body>
    </html>
  )
}
